### ISSUE TITLE
Not Listed in NPM packages

### ISSUE THREAD

**Issue by rgant** [stylelint-stylistic/stylelint-stylistic#12]
### What steps are needed to reproduce the bug?

```
$ npm add -D @stylistic/stylelint-plugin
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@stylistic%2fstylelint-plugin - Not found
npm ERR! 404 
npm ERR! 404  '@stylistic/stylelint-plugin@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/rgant/.npm/_logs/2023-12-18T16_11_55_957Z-debug-0.log
```

### What Stylelint configuration is needed to reproduce the bug?

Any

### How did you run Stylelint?

npm add -D @stylistic/stylelint-plugin

### Which version of Stylelint are you using?

15.0.0

### What did you expect to happen?

Package to be installed.

### What actually happened?

404 Error

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

Push the package to the registry.

**Comment by rgant** [comment]
Also annoying that `'@stylistic/at-rule-name-space-after': always` needs to be quoted in YAML

**Comment by firefoxic** [comment]
Yeah, I just found out a few minutes ago that it won't be possible to publish the package under a new name until Wednesday. So I just [unmarked the old package as deprecated](https://www.npmjs.com/package/stylelint-codeguide). Sorry for the inconvenience.

**Comment by firefoxic** [comment]
> Also annoying that `'@stylistic/at-rule-name-space-after': always` needs to be quoted in YAML

The prefix is renamed for consistency with the plugins of the [ESLint Stylistic](https://eslint.style) project, in the organization of which Stylelint Stylistic will be published.

**Comment by carlosjeurissen** [comment]
Seems it is available on NPM now:
https://www.npmjs.com/package/@stylistic/stylelint-plugin

**Comment by firefoxic** [comment]
Yeah, I'm sorry. I forgot to announce and close this issue.

Belatedly, but congratulations on the release 🎉
