### ISSUE TITLE
Usage with stylelint 16.8.2 creates deprecation warnings

### ISSUE THREAD

**Issue by Cherry** [stylelint-stylistic/stylelint-stylistic#35]
As of [stylelint 16.8.2](https://github.com/stylelint/stylelint/releases/tag/16.8.2), many deprecations are being thrown for lots of rules:

```
(node:41128) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/media-query-list-comma-space-after" instead.
```

https://github.com/stylelint/stylelint/pull/7895 seems to be what introduced this.

**Comment by Mouvedia** [comment]
Until this is fixed, you can use [quietDeprecationWarnings](https://stylelint.io/user-guide/options/#quietdeprecationwarnings).

**Comment by firefoxic** [comment]
Thanks for the report. Already working on it.

**Comment by firefoxic** [comment]
@Cherry @sebbayer the fix is available in [v3.0.1](https://github.com/stylelint-stylistic/stylelint-stylistic/releases/tag/v3.0.1) 🚀

**Comment by Cherry** [comment]
Thank you! ❤️

**Comment by sebbayer** [comment]
@firefoxic that was fast, thank you!
