### ISSUE TITLE
Add `messageArgs`

### ISSUE THREAD

**Issue by Mouvedia** [stylelint-stylistic/stylelint-stylistic#38]
### What is the problem you're trying to solve?

see https://github.com/stylelint/stylelint/pull/6589#discussion_r1103709616

> [Experimental feature: some rules support message arguments.](https://stylelint.io/user-guide/configure/#message)

### What solution would you like to see?

Add `messageArgs` to some or all rules.

**Comment by firefoxic** [comment]
@Mouvedia Thanks for the report 🤝
